### PR TITLE
Added Math Scripts

### PR DESCRIPTION
**Pull request by Arun-Kumar-Rathod**
Hello there :D I've added a folder called Math Scripts with Scripts related to maths in it please accept PR. Thank you :)

### CODE REVIEW

**Comment by Arun-Kumar-Rathod** [comment]
Hello there @sarthakroy2002  can you please accept the PR :)

**Comment by sarthakroy2002** [comment]
First check what you are committing.

**Comment by Arun-Kumar-Rathod** [comment]
Hello there @sarthakroy2002 I've added bash scripts which use math in it

**Comment by Arun-Kumar-Rathod** [comment]
sorry my mistake can you please remove the spam tag if possible:)

**Comment by sarthakroy2002** [comment]
> sorry my mistake can you please remove the spam tag if possible:)

I'm following Hacktoberfest Guidelines... Also u spammed. Maintainers are not free all time... never tag them unnecessarily.

**Pull request closed without merging**
